# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzGwropbDL7HPVeMQWheT-SCJyHBEdvM
"""

!pip install -q datasets albumentations scikit-learn timm

from datasets import load_dataset
import numpy as np

print("Loading APTOS dataset from Hugging Face...")

ds = load_dataset(
    "sngsfydy/aptos",
    cache_dir="/content/drive/MyDrive/hf_cache"
)

dataset = ds["train"]

print(ds)

print(f"\nTotal images: {len(dataset)}")

print("\nFeatures:")
print(dataset.features)

labels = dataset["label"]

unique, counts = np.unique(labels, return_counts=True)

print("\nClass distribution:")
for cls, count in zip(unique, counts):
    print(f"Class {cls}: {count}")

import io
import cv2
import numpy as np
from PIL import Image

import torch
from torch.utils.data import Dataset, WeightedRandomSampler, DataLoader

import albumentations as A
from albumentations.pytorch import ToTensorV2

from datasets import load_dataset
from sklearn.utils.class_weight import compute_class_weight


# ──────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────
IMAGE_SIZE       = 512
MINORITY_CLASSES = {1, 3, 4}
MEAN             = [0.485, 0.456, 0.406]
STD              = [0.229, 0.224, 0.225]
CACHE_DIR        = "/content/drive/MyDrive/hf_cache"


# ──────────────────────────────────────────────────────────────
# Load — stays lazy, cached to Drive
# ──────────────────────────────────────────────────────────────
def load_aptos_dataset(cache_dir=CACHE_DIR):
    print("Loading APTOS dataset...")
    ds = load_dataset(
        "sngsfydy/aptos",
        cache_dir=cache_dir
    )["train"]

    ds = ds.train_test_split(
        test_size=0.2,
        stratify_by_column="label",
        seed=42
    )

    print(f"Train: {len(ds['train'])} | Val: {len(ds['test'])}")
    print(f"\nTrain class distribution:")
    train_labels = ds["train"]["label"]
    unique, counts = np.unique(train_labels, return_counts=True)
    for cls, count in zip(unique, counts):
        print(f"  Class {cls}: {count}")

    return ds["train"], ds["test"]


# ──────────────────────────────────────────────────────────────
# Ben Graham Preprocessing
# ──────────────────────────────────────────────────────────────
def ben_graham_preprocess(img: np.ndarray, sigma: int = 10) -> np.ndarray:
    blurred   = cv2.GaussianBlur(img, (0, 0), sigma)
    processed = cv2.addWeighted(img, 4, blurred, -4, 128)
    return processed


# ──────────────────────────────────────────────────────────────
# Green Channel
# ──────────────────────────────────────────────────────────────
def extract_green_channel(img: np.ndarray) -> np.ndarray:
    green = img[:, :, 1]
    return np.stack([green, green, green], axis=2)


# ──────────────────────────────────────────────────────────────
# Augmentations
# ──────────────────────────────────────────────────────────────
def get_transforms(split: str, image_size: int = IMAGE_SIZE) -> A.Compose:

    if split in ("val", "test"):
        return A.Compose([
            A.Resize(image_size, image_size),
            A.Normalize(mean=MEAN, std=STD),
            ToTensorV2()
        ])

    if split == "majority":
        return A.Compose([
            A.Resize(image_size, image_size),
            A.HorizontalFlip(p=0.5),
            A.VerticalFlip(p=0.5),
            A.RandomRotate90(p=0.5),
            A.RandomBrightnessContrast(p=0.3),
            A.Normalize(mean=MEAN, std=STD),
            ToTensorV2()
        ])

    if split == "minority":
        return A.Compose([
            A.Resize(image_size, image_size),
            A.HorizontalFlip(p=0.5),
            A.VerticalFlip(p=0.5),
            A.RandomRotate90(p=0.5),
            A.RandomBrightnessContrast(p=0.4),
            A.ShiftScaleRotate(
                shift_limit=0.1,
                scale_limit=0.15,
                rotate_limit=20,
                p=0.5
            ),
            A.GridDistortion(p=0.3),
            A.ElasticTransform(p=0.2),
            A.CLAHE(clip_limit=3.0, p=0.4),
            A.CoarseDropout(
                max_holes=8,
                max_height=32,
                max_width=32,
                p=0.2
            ),
            A.Normalize(mean=MEAN, std=STD),
            ToTensorV2()
        ])


# ──────────────────────────────────────────────────────────────
# Dataset
# ──────────────────────────────────────────────────────────────
class APTOSDataset(Dataset):

    def __init__(
        self,
        hf_dataset,
        split,
        image_size=IMAGE_SIZE,
        use_ben_graham=True,
        use_green_channel=True
    ):
        assert split in ("train", "val", "test"), \
            f"Invalid split: '{split}'"

        self.ds                = hf_dataset
        self.split             = split
        self.use_ben_graham    = use_ben_graham
        self.use_green_channel = use_green_channel

        self.majority_tf = get_transforms("majority", image_size)
        self.minority_tf = get_transforms("minority", image_size)
        self.val_tf      = get_transforms("val",      image_size)

    def __len__(self):
        return len(self.ds)

    def __getitem__(self, idx):
        sample = self.ds[idx]
        label  = int(sample["label"])

        # PIL → RGB numpy — one image at a time
        img = sample["image"].convert("RGB")
        img = np.array(img)

        # Ben Graham first — normalize lighting on full RGB
        if self.use_ben_graham:
            img = ben_graham_preprocess(img)

        # Green channel — vessels clearer after lighting normalization
        if self.use_green_channel:
            img = extract_green_channel(img)

        # Pick augmentation
        if self.split == "train":
            tf = self.minority_tf if label in MINORITY_CLASSES \
                 else self.majority_tf
        else:
            tf = self.val_tf

        augmented = tf(image=img)
        return (
            augmented["image"],
            torch.tensor(label, dtype=torch.long)
        )


# ──────────────────────────────────────────────────────────────
# Class Weights + Sampler
# ──────────────────────────────────────────────────────────────
def get_class_weights(labels) -> torch.Tensor:
    weights = compute_class_weight(
        class_weight="balanced",
        classes=np.array([0, 1, 2, 3, 4]),
        y=labels
    )
    print("Class weights:")
    for i, w in enumerate(weights):
        print(f"  Class {i}: {w:.3f}")
    return torch.FloatTensor(weights)


def get_sampler(hf_dataset) -> WeightedRandomSampler:
    labels         = hf_dataset["label"]
    class_weights  = get_class_weights(labels)
    sample_weights = [float(class_weights[l]) for l in labels]

    return WeightedRandomSampler(
        weights     = torch.FloatTensor(sample_weights),
        num_samples = len(sample_weights),
        replacement = True
    )


# ──────────────────────────────────────────────────────────────
# Sanity Check
# ──────────────────────────────────────────────────────────────
if __name__ == "__main__":

    train_ds, val_ds = load_aptos_dataset()

    train_dataset = APTOSDataset(train_ds, split="train")
    val_dataset   = APTOSDataset(val_ds,   split="val")

    sampler = get_sampler(train_ds)

    train_loader = DataLoader(
        train_dataset,
        batch_size  = 16,
        sampler     = sampler,
        num_workers = 0,        # 0 on Colab — avoids multiprocessing errors
        pin_memory  = True
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size  = 16,
        shuffle     = False,
        num_workers = 0,        # 0 on Colab
        pin_memory  = True
    )

    images, labels = next(iter(train_loader))

    print(f"\n✅ Sanity check passed!")
    print(f"   Image shape : {images.shape}")    # [16, 3, 512, 512]
    print(f"   Labels      : {labels.tolist()}")
    print(f"   Min pixel   : {images.min():.3f}")
    print(f"   Max pixel   : {images.max():.3f}")

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/mohamadkhabazy-bit/retinopathy-screening.git

import shutil
shutil.copy("/content/project.ipynb", "/content/retinopathy-screening/notebooks/01_dataset_pipeline.ipynb")

# %cd /content/retinopathy-screening
!git config user.email "mohamadkhabazy@gmail.com"
!git config user.name "mohamadkhabazy-bit"
!git add .
!git commit -m "feat: dataset pipeline — Phase 1 complete"
!git push https://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N@github.com/mohamadkhabazy-bit/retinopathy-screening.git main

!find /content -name "*.ipynb"

